a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está em maiúculas? ', a.isupper())
print('Está em munúsculas? ', a.islower())
print('A primeira letra é maiúscula? ', a.istitle())