recebe_dados = input("Digite qualquer coisa: ")
print("O tipo primitivo desse valor é: ", type(recebe_dados))
print("Contém apenas espaços? ", recebe_dados.isspace())
print("É um número? ", recebe_dados.isnumeric())
print("É alfabético? ", recebe_dados.isalpha())
print("É alfanumérico? ", recebe_dados.isalnum())
print("Está em maiúsculas? ", recebe_dados.isupper())
print("Está em minúsculas? ", recebe_dados.islower())
print("Está capitalizada? ", recebe_dados.istitle())