recebe_numero = int(input('Digite um número inteiro: '))

print(f'{recebe_numero} x  1 = {recebe_numero *  1}.')
print(f'{recebe_numero} x  2 = {recebe_numero *  2}.')
print(f'{recebe_numero} x  3 = {recebe_numero *  3}.')
print(f'{recebe_numero} x  4 = {recebe_numero *  4}.')
print(f'{recebe_numero} x  5 = {recebe_numero *  5}.')
print(f'{recebe_numero} x  6 = {recebe_numero *  6}.')
print(f'{recebe_numero} x  7 = {recebe_numero *  7}.')
print(f'{recebe_numero} x  8 = {recebe_numero *  8}.')
print(f'{recebe_numero} x  9 = {recebe_numero *  9}.')
print(f'{recebe_numero} x 10 = {recebe_numero * 10}.')